local guide = WoWPro:RegisterGuide("BFA Cooking","Profession","BFA Cooking", "Spoony", "Neutral")
WoWPro:GuideIcon(guide,"PRO",171)
WoWPro:GuideName(guide, "BFA Cooking")
WoWPro:GuideLevels(guide)
WoWPro:GuideSteps(guide, function()
return [[
N Disclaimer|N| We are not saying you have to follow this guide, we have provided it as a base guideline only so any errors/suggestions please post in the discord group as normal. You may have a better way of levelling your profession, if so we welcome suggestions on edits that can be made.
N Cooking Trainers|N| You can find T'sarah the Royal Chef in Dazar'alor. She is located in the kitchen right behind your mission table near the Great Seal in the Dazar'alor temple.You can walk up to a guard in Dazar'alor then ask where the Cooking trainer is. Asking the guard will place a red marker on your map at the trainer's location.|FACTION|Horde|
N Cooking Trainers|N|"Cap'n" Byron Mehlsack is in Boralus at the Tradewinds Market.You can walk up to a guard in Boralus then ask where the Cooking trainer is. Asking the guard will place a red marker on your map at the trainer's location.|FACTION|Alliance|
N Recipe ranks|N|Every BfA cooking recipe has 3 ranks. Higher rank recipes allow you to cook more food for the same materials, and higher rank recipes also give skill points much longer. (the exceptions are the new Feast recipes, you always make one, but it will cost fewer materials)
N Unlocking World Quests|N|Some of the Rank 3 recipes are locked behind World Quests. These are not required to reach 175, but you will save some gold if you can get them. To unlock World Quest, you must complete the first steps of War Campaign until you get the quest Uniting Zandalar|FACTION|Horde|
N Unlocking World Quests|N|Some of the Rank 3 recipes are locked behind World Quests. These are not required to reach 175, but you will save some gold if you can get them. To unlock World Quest, you must complete the first steps of War Campaign until you get the quest Uniting Kul Tiras|FACTION|Alliance|
N Cooking Reagents|N|The following Cooking reagents are all sold by Hanul Swiftgale.Wild Flour,Choral Honey,Powdered Sugar,Foosaka,Wild Berries,Fresh Potato.|FACTION|Horde|
N Cooking Reagents|N|The following Cooking reagents are all sold by Henrick Wyther.Wild Flour,Choral Honey,Powdered Sugar,Foosaka,Wild Berries,Fresh Potato.|FACTION|Alliance|
N Extracting Oil|N| You can extract Aromatic Fish Oil from any Battle for Azeroth fish. You have to right-click the fish you caught, and it will convert the fish into oil.
N Fish|N| Fishes no longer come from one specific zone. Instead, you can find 3 types of fish in the Kul Tiras zones, 3 in the Zandalar zones, 2 in Nazjatar, 1 in Mechagon and you can fish 2 in all zones.
N Fish|N|Mechagon:Ionized Minnow - Nazjatar:Viper Fish,Mauve Stinger - Kul Tiras:Frenzied Fangtooth and Lane Snapper - Fished from seas/oceans - Tiragarde Perch - Fished from rivers/lakes - Zandalar:Slimy Mackerel and Sand Shifter - Fished from seas/oceans.Redtail Loach - Fished from rivers/lakes - All zones:Great Sea Catfish - Rivers and lakes. (except Nazjatar), Midnight Salmon - Everywhere. (rare fish, around 3% catch rate)
L 1 - 35|N| 34 x Mon'Dazi - 340 Wild Flour, 170 Foosaka, 68 Aromatic Fish Oil, 136 Powdered Sugar
L 35 - 50|N| Learn the Rank 2 recipes from your trainer. (You don't have to make Kul Tiramisu, you can make any other dessert recipe) - 15 x Rank 2 - Kul Tiramisu - 150 Wild Flour, 75 Foosaka, 30 Aromatic Fish Oil, 75 Major's Frothy Coffee
L 50 - 75|N| Make 25 from one of the these three:25 x Seasoned Loins - 250 Stringy Loins, 125 Foosaka or 25 x Honey-Glazed Haunches - 250 Meaty Haunch, 125 Choral Honey or 25 x Sailor's Pie - 250 Briny Flesh, 125 Wild Flour, 100 Foosaka, 100 Fresh Potato. If you make Seasoned Loins, don't vendor them! Sometimes you can use them for Warfront Contributions quests when the Warfronts are up.
N Note|N| These meats are usually really cheap, so I recommend to switch to these dishes at 50, but if they are expensive on your realm, then it's better to make more Rank 2 - Kul Tiramisu up to around 75. As a general rule, if 1 Aromatic Fish Oil cost around the same as these meats, then you should make Kul Tiramisu because even if you have to craft 2-3 for a skill point, you would still only need 4-6 Fish Oil, instead of the 10 meats.
L 75 - 140|N| Learn the Rank 2 recipes from your trainer. Make around 120 from one of these three:Rank 2 - Seasoned Loins - 800 Stringy Loins, 400 Foosaka or Rank 2 - Honey-Glazed Haunches - 800 Meaty Haunch, 400 Choral Honey or Rank 2 - Sailor's Pie - 800 Briny Flesh, 400 Wild Flour, 320 Foosaka, 320 Fresh Potato. These will be green for the last 10 points, so you might have to make more.
N Rank 3 recipes|N|If you can get the rank 3 of these recipes, then you can make them until 150.Recipe: Honey-Glazed Haunches - Reward from the World Quest: "Work Order: Honey-Glazed Haunches" (this one will show up randomly sometimes on your map) - Recipe: Seasoned Loins - Requires Tortollan Seekers - Revered. Sold by Collector Kojo - Recipe: Sailor's Pie - Reward from the World Quest: "Work Order: Sailor's Pie" (this one will show up randomly sometimes on your map)
L 140 - 155|N|Visit your trainer Rolm at Nazjatar and learn the new recipes. (You have to finish the first few intro quest at Nazjatar before you can see these NPCs.)Then make 15 x Rank 1 - Abyssal-Fried Rissole - 120 Moist Fillet, 45 Foosaka, 75 Wild Flour. You can make other recipes, but Moist Fillet should be the cheapest.|FACTION|Horde|
L 140 - 155|N|Visit your trainer Instructor Ulooaka at Nazjatar and learn the new recipes. (You have to finish the first few intro quest at Nazjatar before you can see these NPCs.)Then make 15 x Rank 1 - Abyssal-Fried Rissole - 120 Moist Fillet, 45 Foosaka, 75 Wild Flour. You can make other recipes, but Moist Fillet should be the cheapest.|FACTION|Alliance|
L 155 - 175|N| Learn the rank 2 recipes. Then make 25 x Rank 2 - Abyssal-Fried Rissole - 200 Moist Fillet, 75 Foosaka, 125 Wild Flour
N I hope you liked this guide, congratulations on reaching 175!

]]
end)