local guide = WoWPro:RegisterGuide("BFA Inscription","Profession","BFA Inscription", "Spoony", "Neutral")
WoWPro:GuideIcon(guide,"PRO",197)
WoWPro:GuideLevels(guide)
WoWPro:GuideName(guide, "BFA Inscription")
WoWPro:GuideSteps(guide, function()
return [[

N Note |N|Inscription is the best combined with Herbalism because you can save a lot of gold by farming the needed herbs
N Inscription Trainers:|N|You can find Chronicler Grazzul in Dazar'alor at the Terrace of Crafters.You can walk up to a guard in Dazar'alor then ask where the Inscription trainer is. Asking the guard will place a red marker on your map at the trainer's location.|FACTION|Horde|
N Inscription Trainers:|N|You can find Zooey Inksprocket is in Boralus at the Tradewinds Market.You can walk up to a guard in Boralus then ask where the Inscription trainer is. Asking the guard will place a red marker on your map at the trainer's location.|FACTION|Alliance|
N Note|N| You can buy Light Parchment, Distilled Water, and Acacia Powder from the Inscription Supply vendors near your trainer, or from your trainer directly.
N Milling and Pigments|N|Ultramarine Pigment, Crimson Pigment, and Viridescent Pigment come from milling any herb from Zandalar or Kul Tiras. (Anchor Weed, Akunda's Bite, Winter's Kiss, Sea Stalk, Star Moss, Siren's Pollen, Riverbud)
N Pigment rarity:|N|Ultramarine Pigment ~75% - Crimson Pigment ~25% - Viridescent Pigment ~10% ( Anchor Weed gives ~30%)
N 1 - 50|N|You will need around 900 Ultramarine Ink, 550 Crimson Ink, and 50 Viridescent Ink to reach 145. So, since milling gives skill points up to 25, you should mill around 100-150 from one herb then turn all your pigments into inks until you reach 50. Don't mill more herbs than you need to reach 50 because you will unlock Mass Mill at 50 which will give skill points up to 80.
N 50 - 80|N|Use the Mass Mill spell that you learned from your trainer to Mass mill any herb. You will use the pigments to make Inks, and then use the Inks to level up Inscription, so these are basically free skill points. You will need to mill around 1000 herbs to reach 80, but after you reach 80 you could stop and just buy the inks from the Auction House. But it's usually still cheaper to just mill herbs and make the inks..Make War-Scroll of Battle Shout if you don't want to mill herbs.
N 80 - 85|N|8 x War-Scroll of Battle Shout - 64 Crimson Ink. This recipe will be yellow, so you will have to make around 5-8.
N 85 - 140|N|60 x Rank 2 - Contract: 7th Legion - 900 x Ultramarine Ink, 480 x Crimson Ink.|FACTION|Alliance|
N 85 - 140|N|60 x Rank 2 - Contract: The Honorbound - 900 x Ultramarine Ink, 480 x Crimson Ink.|FACTION|Horde|
N Recipes|N| These recipes are locked behind Honored reputation, but reaching honored with one of these factions is really easy. You can reach Honored just by completing your War Campaign quests and then doing a few faction Assaults. Rank 2 - Recipe: Contract: 7th Legion is sold by Vindicator Jaelaana. It requires 7th Legion Honored reputation.Rank 2 - Recipe: Contract: The Honorbound is sold by Ransa Greyfeather. Requires The Honorbound Honored reputation
N Alternative recipes|N|It's a good idea to make a few different kinds of contract recipes because it's easier to sell them at the Auction House. You should only make these if you can buy the rank 2 version because Rank 2 recipes will give skill points longer, and also cost fewer materials, and you should only make them until they turn yellow at 105. (unless you get the rank 3)
N Note|N|Check your map every day and look for Inscription World quests like "Work Order: Contract: Talanji's Expedition". These rewards you with the rank 3 recipe, which is even better and you can make contracts up to around 130. (you have to get the rank 2 to learn the rank 3)
N Rank 2 recipes|N|Contract: Talanji's Expedition sold by Provisioner Lija, Requires Talanji's Expedition Honored reputation. Contract: Voldunai sold by Hoarder Jena, Requires Voldunai Honored reputation. Contract: Zandalari Empire sold by Natal'hakata,It requires Zandalari Empire Honored reputation.|FACTION|Horde|
N Rank 2 recipes|N|Contract: Order of Embers sold by Quartermaster Alcorn, It requires Order of Embers Honored reputation. Contract: Proudmoore Admiralty sold by Provisioner Fray, It requires Proudmoore Admiralty Honored reputation. Contract: Storm's Wake sold by Sister Lilyana,It requires Storm's Wake Honored reputation.|FACTION|Alliance|
N Neutral|N|Contract: Champions of Azeroth sold by Collector Kojo. Requires Tortollan Seekers Honored. Contract: Tortollan Seekers sold by Collector Kojo. Requires Tortollan Seekers Honored reputation.
N 140 - 145|N| You can continue to make contracts, but I recommend switching to Darkmoon Cards because you will only get skill points every 2-3 craft from the contracts, and you should have some Viridescent Ink from milling anyway. 5 x Rank 2 - Darkmoon Card of War - 5 Light Parchment, 50 Viridescent Ink, 5 Expulsom. If you are Revered with the Tortollan Seekers, then you can buy the Rank 3 Recipe: Darkmoon Card of War from Collector Kojo. The rank 3 recipe cost fewer Viridescent Ink.
N 145 - 175|N| Visit your trainer Narv at Nazjatar and learn the new recipes. (You have to finish the first few intro quest at Nazjatar before you can see these NPCs.)100 x Maroon Ink - 100 Distilled Water, 100 Maroon Pigment. You will need to mill around 150 Zin'anthid to get enough Maroon Pigment.  But don't mill all of your herbs because you will learn Mass Mill Zin'anthid at 155 and you can get 4-5 skill points by Mass milling the rest of your herbs, so you should mill herbs/make inks until you reach 155, then mass mill the rest.|FACTION|Horde|
N 145 - 175|N| Visit your trainer Instructor Okanu at Nazjatar and learn the new recipes. (You have to finish the first few intro quest at Nazjatar before you can see these NPCs.)100 x Maroon Ink - 100 Distilled Water, 100 Maroon Pigment. You will need to mill around 150 Zin'anthid to get enough Maroon Pigment.  But don't mill all of your herbs because you will learn Mass Mill Zin'anthid at 155 and you can get 4-5 skill points by Mass milling the rest of your herbs, so you should mill herbs/make inks until you reach 155, then mass mill the rest.|FACTION|Alliance|
N I hope you liked this guide, congratulations on reaching 175!
]]
end)
